services:
  Shared.Logger:
    class: ../../../../../Contexts/Shared/infrastructure/WinstonLogger
    arguments: []

  Marketplace.Shared.MongoConfig:
    factory:
      class: ../../../../../Contexts/Marketplace/Shared/infrastructure/persistence/mongo/MongoConfigFactory
      method: 'createConfig'

  Marketplace.Shared.ConnectionManager:
    factory:
      class: ../../../../../Contexts/Shared/infrastructure/persistence/mongo/MongoClientFactory
      method: 'createClient'
    arguments: ['marketplace', '@Marketplace.Shared.MongoConfig']

  Marketplace.Shared.CommandHandlers:
    class: ../../../../../Contexts/Shared/infrastructure/CommandBus/CommandHandlers
    arguments: ['!tagged commandHandler']

  Marketplace.Shared.domain.CommandBus:
    class: ../../../../../Contexts/Shared/infrastructure/CommandBus/InMemoryCommandBus
    arguments: ['@Marketplace.Shared.CommandHandlers']

  Marketplace.Shared.QueryHandlers:
    class: ../../../../../Contexts/Shared/infrastructure/QueryBus/QueryHandlers
    arguments: ['!tagged queryHandler']

  Marketplace.Shared.domain.QueryBus:
    class: ../../../../../Contexts/Shared/infrastructure/QueryBus/InMemoryQueryBus
    arguments: ['@Marketplace.Shared.QueryHandlers']

  Marketplace.Shared.RabbitMQConfig:
    factory:
      class: ../../../../../Contexts/Marketplace/Shared/infrastructure/RabbitMQ/RabbitMQConfigFactory
      method: 'createConfig'

  Marketplace.Shared.domain.EventBus:
    factory:
      class: ../../../../../Contexts/Marketplace/Shared/infrastructure/RabbitMQ/RabbitMQEventBusFactory
      method: 'create'
    arguments:
      [
        '@Marketplace.Shared.DomainEventFailoverPublisher',
        '@Marketplace.Shared.RabbitMQConnection',
        '@Marketplace.Shared.RabbitMQqueueFormatter',
        '@Marketplace.Shared.RabbitMQConfig'
      ]

  Marketplace.Shared.RabbitMQQueueFormatter:
    class: ../../../../../Contexts/Shared/infrastructure/EventBus/RabbitMQ/RabbitMQqueueFormatter
    arguments: ['marketplace']

  Marketplace.Shared.RabbitMQConnection:
    class: ../../../../../Contexts/Shared/infrastructure/EventBus/RabbitMQ/RabbitMqConnection
    arguments: ['@Marketplace.Shared.RabbitMQConfig']

  Marketplace.Shared.RabbitMQqueueFormatter:
    class: ../../../../../Contexts/Shared/infrastructure/EventBus/RabbitMQ/RabbitMQqueueFormatter
    arguments: ['marketplace']

  Marketplace.Shared.DomainEventFailoverPublisher:
    class: ../../../../../Contexts/Shared/infrastructure/EventBus/DomainEventFailoverPublisher/DomainEventFailoverPublisher
    arguments: ['@Marketplace.Shared.ConnectionManager']
